# This file contains values from Cookiecutter

default_context:
  project_name: "wrapper"
  project_description: "A wrapper for DREEM for the Herschlag lab"
  organization: "Herschlag Lab"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "yvesmartindestaillades"
  email: "yves@martin.yt"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
