[build-system]
requires = ["setuptools<61"]
build-backend = "setuptools.build_meta"

[project]
name = "DREEM_Herschlag"
authors = [{name = "Yves Martin des Taillades", email = "yves@martin.yt"}]
dynamic = ["version", "description"]
